config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :trainers, only: [:show] do
    resources :pokemons, only: [:create]
  end

  resources :pokemons, only: :destroy do
    resources :pokemon_types, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trainer
  has_many :pokemon_types
  has_many :types, through: :pokemon_types
  validates :name, :image_url, presence: true
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
  validates :type, uniqueness: { scope: :pokemon }
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :name, :banner_url, presence: true
  validates :name, length: { minimum: 2 }
  has_many :pokemons
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  def new
    # 1. Find the parent! In this case pokemon
    @pokemon = Pokemon.find(params[:pokemon_id])
    # 2. Instantiate the empty child, in this case, PokemonType
    @pokemon_type = PokemonType.new
  end

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    # @pokemon_type = PokemonType.new
    # @type = Type.find(params[:pokemon_type][:type])
    # @pokemon_type.type = @type
    # @pokemon_type.pokemon = @pokemon
    # Below, AFTER USING MULTIPLE TYPES
    types = Type.where(id: params[:pokemon_type][:type])
    types.each do |type|
      pokemon_type = PokemonType.new(type: type, pokemon: @pokemon)
      pokemon_type.save
    end

    redirect_to trainer_path(@pokemon.trainer)
  end

  private

  def pokemon_type_params
    params.require(:pokemon_type).permit(:type)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def create
    @pokemon = Pokemon.new(pokemon_params)
    @trainer = Trainer.find(params[:trainer_id])
    @pokemon.trainer = @trainer
    if @pokemon.save
      redirect_to trainer_path(@trainer) #=> /trainers/5346
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy
    redirect_to trainer_path(@pokemon.trainer), status: :see_other
  end

  private

  # STRONG_PARAMS
  def pokemon_params
    params.require(:pokemon).permit(:name, :image_url)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def show
    @trainer = Trainer.find(params[:id])
    @pokemon = Pokemon.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GottaCatchThemAll1563</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemon_types/new.html.erb
<h1>Add a type</h1>

<%= simple_form_for([@pokemon, @pokemon_type]) do |f| %>
  <%= f.input :type, collection: Type.all, input_html: { multiple: true } %>
  <%= f.submit 'Add type', class: 'btn btn-primary' %>
<% end %>

app/views/trainers/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @trainer.banner_url %>);">
  <div class="container">
    <h1><%= @trainer.name %></h1>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <% @trainer.pokemons.each do |pokemon| %>
      <div class="col-12 col-md-4 mb-3">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= pokemon.image_url %>)">
          <%= pokemon.name %>
          <%= link_to '+', pokemon_path(pokemon), class: 'remove__link', data: { turbo_method: :delete, turbo_confirm: 'Are you SURE?!?!?!?!?! Send to the pc!'} %>
          <div class="card__tags">
            <% pokemon.types.each do |type| %>
              <span><%= type.name %></span>
            <% end %>
            <%= link_to '+', new_pokemon_pokemon_type_path(pokemon) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-md-3 bg-white border rounded px-2 py-3">
      <%= simple_form_for([@trainer, @pokemon]) do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit 'Add pokemon', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>